version: '3'
services:
  # container for API
  app:
    build:
      context: .
    ports:
      - 8000:80
    volumes:
      - .:/usr/src/app
      - ./conf/nginx.conf:/etc/nginx/sites-available/app.nginx.conf
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    working_dir: /usr/src/app/api
    command:
      - /bin/bash
      - -c
      - |
        ln -s /etc/nginx/sites-available/app.nginx.conf /etc/nginx/sites-enabled
        service supervisor start
        service nginx restart
        tail -f /dev/null 2>&1
    restart: on-failure