version: '3'
services:
  # container for API
  app:
    build:
      context: .
    ports:
      - 8000:80
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - ./conf/nginx.conf:/etc/nginx/sites-available/app.nginx.conf
      - ./uwsgi.ini:/usr/src/app/api/uwsgi.ini
    working_dir: /usr/src/app/api
    command:
    - /bin/bash
    - -c
    - |
      ln -s /etc/nginx/sites-available/app.nginx.conf /etc/nginx/sites-enabled
      uwsgi --ini uwsgi.ini
      tail -f /dev/null 2>&1
    restart: on-failure
  db:
    image: mysql:5.7
    ports:
      - 3305:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: user123